SQL succeeded but Query is now invalid ('main', 1371, 'accept'): 
UPDATE tasks 
SET do = 'research dropbox api f√ºr datenbank via mobile ',
    priority = 0.0,
    level_id = 0,
    primary_activity_id = 2,
    secondary_activity_id = NULL,
    space_id = 1,
    ilk = 1
WHERE id=148
